export const FuseStatus = Object.freeze({
  PROPOSED: 'PROPOSED',
  ARMED: 'ARMED',
  OPEN: 'OPEN',
  REDUCING: 'REDUCING',
  KILLED: 'KILLED',
  SETTLED: 'SETTLED'
});

export const Reason = Object.freeze({
  INITIAL_OPEN: 'INITIAL_OPEN',
  PROBABILITY_STEP_UP: 'PROBABILITY_STEP_UP',
  PROBABILITY_STEP_DOWN: 'PROBABILITY_STEP_DOWN',
  RISK_CAP_CLAMP: 'RISK_CAP_CLAMP',
  KILL_PROBABILITY: 'KILL_PROBABILITY',
  LOSS_STOP: 'LOSS_STOP',
  EXPIRY_CLOSE: 'EXPIRY_CLOSE',
  OWNER_CANCEL: 'OWNER_CANCEL',
  SETTLEMENT: 'SETTLEMENT',
  NOOP: 'NOOP',
  ORACLE_STALE: 'ORACLE_STALE',
  ORACLE_WIDE: 'ORACLE_WIDE',
  RECONCILE: 'RECONCILE',
  EMERGENCY_KILL: 'EMERGENCY_KILL'
});

export const ALLOWED_TRANSITIONS = Object.freeze({
  PROPOSED: new Set(['ARMED', 'SETTLED']),
  ARMED: new Set(['OPEN', 'KILLED', 'SETTLED']),
  OPEN: new Set(['OPEN', 'REDUCING', 'KILLED', 'SETTLED']),
  REDUCING: new Set(['REDUCING', 'OPEN', 'KILLED', 'SETTLED']),
  KILLED: new Set(['KILLED', 'SETTLED']),
  SETTLED: new Set(['SETTLED'])
});
